name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [17.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
        node-version: ${{ matrix.node }}
      - name: install modules
        run: npm install
